<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWs5Y+4566A5LuL');
$cfg_Cs[6]=array(3,6,1,'57O75YiX5YiG57G7');
$cfg_Cs[2]=array(0,1,1,'5paw6Ze75Yqo5oCB');
$cfg_Cs[3]=array(0,6,1,'5Lqn5ZOB5bGV56S6');
$cfg_Cs[4]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[5]=array(3,6,1,'5p2Q6LSo5YiG57G7');
$cfg_Cs[7]=array(6,6,1,'57O75YiXMQ==');
$cfg_Cs[8]=array(6,6,1,'57O75YiXMg==');
$cfg_Cs[9]=array(5,6,1,'5p2Q6LSoMQ==');
$cfg_Cs[10]=array(5,6,1,'5p2Q6LSoMg==');
$cfg_Cs[11]=array(5,6,1,'5p2Q6LSoMw==');
?>