<tr>
  
    	<td><table background="{dede:global.cfg_templets_skin/}/images/line.gif" border="0" cellpadding="0" cellspacing="0" height="30" width="640">
  <tbody><tr>
    <td align="left" valign="top" width="479"><div style="padding-left:20px; padding-top:7px" class="cc"><a href="[field:arcurl/]" target="_self">[field:title/]</a></div></td>
    <td align="left" valign="top" width="161"><div style="padding-left:20px; padding-top:3px" class="cc">[field:stime/]</div></td>
  </tr>
  
</tbody></table>
		</td>
		
    </tr>