<?php
$z[0]=Array("global","",34,66);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",786,813);
$z[1][4]['name']="cfg_indexurl";
$z[2]=Array("channel","\r\n<a href=\"[field:typelink/]\" target=\"_self\" class=\"menumain_dolphin\">[field:typename/]</a>\r\n",873,1006);
$z[2][4]['type']="top";
$z[3]=Array("global","",1106,1138);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",1353,1385);
$z[4][4]['name']="cfg_templets_skin";

?>