<html>
<head>
    <title></title>
    <style type="text/css">
        body {
            margin:0px auto;
        }
        #fixedLayer {
            position:fixed;
            right: 5px;
            top: 50%;
            width:100px;
            line-height:30px;
            background: #FC6;
            border:1px solid #F90;
        }
    </style>
</head>
<body oncontextmenu=self.event.returnValue=false onselectstart="return false">
<div id="fixedLayer">固定不动</div>
<a href="www.baidu.com"><p>ddddddd</p></a>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
<p>ddddddd</p>
</body>
</html>